import os

out_path = "/Users/khoale/Downloads/tsne_folds_report.html"
plot_dir = "analysis_output_tSNE/fold_plots"

VARIANTS = [
    'ce', 
    'ins2ins', 
    'ins2cls', 
    'full',
    'exclude_ins2ins',
    'exclude_ins2cls',
    'exp_triplet_ins2cls',
    'triplet_only',
    'hierarchical_triplet_only',
    'exp_hierarchical_triplet_ins2cls',
    'full_4class',
    'exp_triplet_ins2cls_4class',
    'hierarchical_triplet_only_4class',
    'qwk_hierarchical_triplet_4class',
    'exp_3pole_local',
    'exp_3pole_global'
]

CHECKPOINTS = ['best_2c_net', 'best_3c_net', 'best_4c_net']
FOLDS = [1, 2, 3, 4, 5]

variant_names = {
    'ce': 'L_CE',
    'ins2ins': 'L_CE + L_Ins2Ins',
    'ins2cls': 'L_CE + L_Ins2Ins + L_Ins2Cls',
    'full': 'L_CE + L_Ins2Ins + L_Ins2Cls + L_Cls2Cls',
    'exclude_ins2ins': 'L_CE + L_Ins2Cls + L_Cls2Cls',
    'exclude_ins2cls': 'L_CE + L_Ins2Ins + L_Cls2Cls',
    'exp_triplet_ins2cls': 'L_CE + L_Ins2Ins + L_Triplet + L_Cls2Cls',
    'triplet_only': 'L_CE + L_Triplet',
    'hierarchical_triplet_only': 'L_CE + L_Hierarchical_Triplet',
    'exp_hierarchical_triplet_ins2cls': 'L_CE + L_Ins2Ins + L_Hierarchical_Triplet + L_Cls2Cls',
    'full_4class': 'L_CE + L_Ins2Ins + L_Ins2Cls + L_Cls2Cls (4-Class)',
    'exp_triplet_ins2cls_4class': 'L_CE + L_Ins2Ins + L_Triplet + L_Cls2Cls (4-Class)',
    'hierarchical_triplet_only_4class': 'L_CE + L_Hierarchical_Triplet (4-Class)',
    'qwk_hierarchical_triplet_4class',
    'exp_3pole_local',
    'exp_3pole_global': 'L_QWK + L_Hierarchical_Triplet (4-Class)'
}

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>t-SNE Per-Fold Analysis</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #0f111a;
            --surface: #1e2130;
            --primary: #6366f1;
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 40px;
        }
        header {
            text-align: center;
            margin-bottom: 50px;
        }
        h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
            background: linear-gradient(90deg, #818cf8, #c084fc);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        p.subtitle {
            color: var(--text-muted);
            font-size: 1.1rem;
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.6;
        }
        .analysis-card {
            background: rgba(30, 33, 48, 0.6);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 12px;
            padding: 20px 30px;
            margin-bottom: 40px;
            backdrop-filter: blur(10px);
        }
        .analysis-card h3 {
            color: #818cf8;
            margin-top: 0;
        }
        .variant-section {
            margin-bottom: 80px;
            border-top: 1px solid rgba(255,255,255,0.1);
            padding-top: 40px;
        }
        .variant-title {
            font-size: 1.8rem;
            margin-bottom: 20px;
            color: #e2e8f0;
        }
        .checkpoint-block {
            margin-bottom: 40px;
        }
        .checkpoint-title {
            font-size: 1.2rem;
            color: var(--text-muted);
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .folds-container {
            display: flex;
            gap: 15px;
            overflow-x: auto;
            padding-bottom: 15px;
        }
        .fold-card {
            flex: 0 0 19%;
            background: var(--surface);
            border-radius: 8px;
            padding: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
            text-align: center;
            transition: transform 0.2s;
        }
        .fold-card:hover {
            transform: translateY(-5px);
        }
        .fold-card img {
            width: 100%;
            border-radius: 4px;
            background: white; /* Plots have white background */
        }
        .fold-label {
            margin-top: 10px;
            font-weight: 600;
            font-size: 0.9rem;
            color: #cbd5e1;
        }
    </style>
</head>
<body>

    <header>
        <h1>Latent Space t-SNE Analysis Across Folds</h1>
        <p class="subtitle">A visual progression of the latent manifold geometry generated by various loss functions. Examining all 5 folds side-by-side reveals the generalizability of the learned decision boundaries.</p>
    </header>

    <div class="analysis-card">
        <h3>🔍 General Observations & Analysis</h3>
        <p><strong>The t-SNE Illusion:</strong> Baseline models (like Cross Entropy) often cluster CN and AD adequately but fail severely on intermediate stages (sMCI and pMCI). Because these classes overlap in biological severity, standard categorical losses arbitrarily mix them or force them into non-linear configurations. A linear classifier struggles to resolve this on unseen test folds.</p>
        <p><strong>Hierarchical Triplet Superiority:</strong> The Hierarchical Triplet variants enforce an <em>ordinal manifold</em>. Instead of arbitrary "blobs," the latent space stretches into a spectrum matching disease progression. Notice how the transition from CN (Blue) -> sMCI (Green) -> pMCI (Orange) -> AD (Red) becomes more structured. This mathematical spacing is exactly why these variants generalize better across all 5 folds.</p>
        <p><strong>Fold Variance:</strong> Notice the variance between Folds 1-5. Some test sets are naturally harder. A robust model (like the Hierarchical variants) maintains its ordinal geometry across <em>all</em> folds, whereas weaker models might look okay on Fold 1 but collapse entirely on Fold 3.</p>
    </div>

"""

for variant in VARIANTS:
    v_name = variant_names.get(variant, variant)
    html += f'    <div class="variant-section">\n'
    html += f'        <h2 class="variant-title">{v_name}</h2>\n'
    
    for ckpt in CHECKPOINTS:
        html += f'        <div class="checkpoint-block">\n'
        html += f'            <div class="checkpoint-title">Checkpoint: {ckpt}</div>\n'
        html += f'            <div class="folds-container">\n'
        
        for fold in FOLDS:
            img_filename = f"tsne_{variant}_{ckpt}_fold{fold}.png"
            img_path = f"{plot_dir}/{img_filename}"
            html += f'                <div class="fold-card">\n'
            html += f'                    <img src="{img_path}" alt="Fold {fold}" loading="lazy">\n'
            html += f'                    <div class="fold-label">Fold {fold}</div>\n'
            html += f'                </div>\n'
            
        html += f'            </div>\n'
        html += f'        </div>\n'
        
    html += f'    </div>\n'

html += """
</body>
</html>
"""

with open(out_path, "w") as f:
    f.write(html)

print(f"Report generated successfully at {out_path}")
