experiment:
  name: mri_pet_baseline

data:
  batch_size: 4
  num_workers: 4

model:
  num_classes: 4
  fusion_type: concat
  
  class_names:
    - CN
    - EMCI
    - LMCI
    - AD

training:
  device: cuda:0
  epochs: 40

optimizer:
  lr: 0.001
  weight_decay: 0.001
  momentum: 0.9

scheduler:
  T_0: 10
  T_mult: 3
  eta_min: 1e-5

